name: aerospace_procurement
version: "1.0"
profile: aerospace_procurement
model-paths: ["models"]
seed-paths: ["seeds"]
models:
  aerospace_procurement:
    staging:
      +schema: staging
      +materialized: table
    warehouse:
      +schema: warehouse
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
seeds:
  aerospace_procurement:
    +schema: reference
    supplier_ownership:
      +column_types:
        valid_from: date
        valid_to: date
    psc_group_names:
      +column_types:
        psc_group: text
    price_index_map:
      +column_types:
        psc_group: text
